# .github/workflows/deploy-backend.yml
name: CD - Deploy Backend to Azure

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]  # Trigger on tags for releases
  workflow_dispatch:

permissions:
  id-token: write  # For Azure login
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production  # Protect with approvals if needed

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Build and Publish
      run: dotnet publish Restaurante.Api/Restaurante.Api.csproj --configuration Release --output ./publish

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}  # e.g., 'restaurante-api'
        package: ./publish

    - name: Logout from Azure
      run: az logout

    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
